version: '3.8'

services:
  backend:
    build:
      context: ./backend
    ports:
      - "15022:3000"
    volumes:
      - ./backend/data:/app/data
      - ./backend/uploads:/app/uploads
    environment:
      - PORT=3000
      - PROD_DOMAIN=https://naorin.ykd.dev
      - CORS_ORIGIN=https://naorin.ykd.dev,http://naorin.ykd.dev
      - JWT_SECRET=anosukanugas-secretkey
    restart: unless-stopped
  frontend:
    build:
      context: ./frontend
      args:
        VITE_API_BASE_URL: "https://naorin.ykd.dev"
    ports:
      - "15021:80"
    depends_on:
      - backend
    restart: unless-stopped