services:
  frontend:
    build:
      context: ./frontend
      args:
        VITE_API_BASE_URL: "https://ykd.dev:15022" 
    ports:
      - "15021:80"
    restart: unless-stopped

  backend:
    build:
      context: ./backend
    ports:
      - "15022:3000"
    volumes:
      - ./backend/data:/app/data
      - ./backend/uploads:/app/uploads
    environment:
      - PORT=3000
      - PROD_DOMAIN=https://ykd.dev:15021
      - CORS_ORIGIN=http://ykd.dev:15021,https://ykd.dev:15021
      - JWT_SECRET=anosukanugas-secretkey
    restart: unless-stopped